name = "REX 2024"

[orientation]
mandatory_tag = "BLACKOUT"
filename = "orientation.csv"

[csv]
# String format used for parsing dates in the CSV, see strftime.net
date_format = "%m/%d/%Y %H:%M"

# Start and end dates of REX, in YYYY-MM-DD
[dates]
start = "2024-08-25" #Sunday after FPOPs end
end = "2024-08-28" # Date of FYRE
# Events that start before this hour will be considered as starting the day before in the booklet
hour_cutoff = 4

# Hardcoding a color for each dorm based on the primary color on their website
[colors.dorms]
"Baker House" = "#005399"
"Burton Conner" = "#cc4331"
"East Campus" = "#aa0000"
"MacGregor House" = "#dc3545"
"Maseeh Hall" = "#1589ff"
"McCormick Hall" = "#293142"
"New House" = "#eaecf9"
"Chocolate City" = "#ffed2e"
"French House" = "#3357cc"
"German House" = "#ff0000"
"iHouse" = "#c78665"
"Juniper" = "#06446c"
"La Casa" = "#e10909"
"New Vassar" = "#afe6af"
"Next House" = "#2c3e50"
"Random Hall" = "#fd5295"
"Simmons Hall" = "#25aae1"
"Campus Wide!" = "#3d93b8" # DormCon color

[colors.tags]
"tour"="#34495e"
"signature"="#f1c40f"
"updated"="#e67e22"
"food"="#27ae60"
"party"="#9b59b6"
"social"="#e74c3c"
"games"="#3498db"
"art"="#1abc9c"

# These control which emoji appear for a tag in the booklet
[tag_emoji]
"food"="ğŸ´"
"party"="ğŸ‰"
"social"="ğŸ‘¥"
"games"="ğŸ²"
"art"="ğŸ¨"


