name = "REX 2025"
rename_dormcon_to = "Campus Wide!"

[orientation]
mandatory_tag = "mandatory"
filename = "orientation.csv"
include_in_booklet = true

[csv]
# String format used for parsing dates in the CSV, see strftime.net
date_format = "%m/%d/%Y %H:%M"

# Start and end dates of REX, in YYYY-MM-DD
[dates]
start = "2025-08-23" # Saturday after FPOPs end
end = "2025-08-27"   # Date of FYRE
# Events that start before this hour will be considered as starting the day before in the booklet
hour_cutoff = 4

# List of dorms with REX chair contact emails, available at https://groups.mit.edu/webmoira/list/dorms-rex
[dorms.rex_contact]
"Baker House" = "baker-rex-chairs"
"Burton Conner" = "bc-rush"
"East Campus" = "ec-rex-chairs-25"
"MacGregor House" = "mac-rex-chairs"
"Maseeh Hall" = "maseeh-rex-chair"
"McCormick Hall" = "mccormick-rex"
"New House" = "nh-rush"
"New Vassar" = "nv-rex-chair"
"Next House" = "next-rex-comm"
"Random Hall" = "random-rush-chair"
"Simmons Hall" = "simmons-frosh-chairs"
"DormCon" = "dormcon-rexvp"

# List of subdorms in each dorm that equals the main dorm (eg. houses in New House), mainly for contacting REX chairs
[dorms.subdorms]
"Chocolate City" = "New House"
"French House" = "New House"
"German House" = "New House"
"iHouse" = "New House"
"Juniper" = "New House"
"La Casa" = "New House"
"Indigenous Living Community" = "Burton Conner"

# Hardcoding a color for each dorm based on the primary color on their website
[colors.dorms]
"Baker House" = "#005399"
"Burton Conner" = "#cc4331"
"Indigenous Living Community" = "#cc4331"
"East Campus" = "#aa0000"
"MacGregor House" = "#ad6f65"
"Maseeh Hall" = "#1f3a6c"
"McCormick Hall" = "#293142"
"New House" = "#e7e9f6"
"Chocolate City" = "#ffed2e"
"French House" = "#3357cc"
"German House" = "#ff0000"
"iHouse" = "#238fc0"
"Juniper" = "#06446c"
"La Casa" = "#e10909"
"New Vassar" = "#A62B0C"
"Next House" = "#34495e"
"Random Hall" = "#cf2661"
"Simmons Hall" = "#25aae1"
"DormCon" = "#618ca0"

[colors.tags]
"tour" = "#1E90FF"
"signature" = "#FFD700"
"updated" = "#808080"
"meal" = "#FF6347"
"snack" = "#FFB347"
"party" = "#C71585"
"social" = "#32CD32"
"games" = "#20B2AA"
"art" = "#8A2BE2"

# These control which emoji appear for a tag in the booklet
[tag_emoji]
"snack" = "ğŸª"
"meal" = "ğŸ´"
"party" = "ğŸ‰"
"social" = "ğŸ‘¥"
"games" = "ğŸ²"
"art" = "ğŸ¨"
