name = "REX 2023"

[csv]
# String format used for parsing dates in the CSV, see strftime.net
date_format = "%m/%d/%Y %H:%M"

# Start and end dates of REX, in YYYY-MM-DD
[dates]
start = "2023-08-27"
end = "2023-08-30"
# Events that start before this hour will be considered as starting the day before in the booklet
hour_cutoff = 4

# Hardcoding a color for each dorm based on the primary color on their website
[colors.dorms]
"Baker House" = "#005399"
"Burton Conner" = "#cc4331"
"East Campus" = "#aa0000"
"MacGregor House" = "#dc3545"
"Maseeh Hall" = "#1589ff"
"McCormick Hall" = "#293142"
"New House" = "#eaecf9"
"Chocolate City" = "#ffed2e"
"French House" = "#3357cc"
"German House" = "#ff0000"
"iHouse" = "#c78665"
"Juniper" = "#06446c"
"La Casa" = "#e10909"
"New Vassar" = "#afe6af"
"Next House" = "#2c3e50"
"Random Hall" = "#fd5295"
"Simmons Hall" = "#25aae1"
"Campus Wide!" = "#a31f34"

[colors.tags]
"signature"="#fac205"
"food"="#0b4008"
"party"="#04d9ff"
"social"="#DF7373"
"games"="#001D4A"
"art"="#3B429F"

# These control which emoji appear for a tag in the booklet
[tag_emoji]
"food"="ğŸ´"
"party"="ğŸ‰"
"social"="ğŸ‘¥"
"games"="ğŸ²"
"art"="ğŸ¨"
