#:schema ./config_schema.json
name = "REX 2025"

[orientation]
mandatory_tag = "mandatory"
file_name = "orientation.csv"
include_in_booklet = true

[csv]
date_format = "%m/%d/%Y %H:%M"

[dates]
start = "2025-08-23"
end = "2025-08-27"
hour_cutoff = 4

# TAGS

[tags.tour]
color = "#1E90FF"

[tags.signature]
color = "#FFD700"

[tags.updated]
color = "#808080"

[tags.meal]
color = "#FF6347"
emoji = "ğŸ´"

[tags.snack]
color = "#FFB347"
emoji = "ğŸª"

[tags.party]
color = "#C71585"
emoji = "ğŸ‰"

[tags.social]
color = "#32CD32"
emoji = "ğŸ‘¥"

[tags.games]
color = "#20B2AA"
emoji = "ğŸ²"

[tags.art]
color = "#8A2BE2"
emoji = "ğŸ¨"

# DORMS

[dorms."Baker House"]
contact = "baker-rex-chairs@mit.edu"
color = "#005399"

[dorms."Burton Conner"]
contact = "bc-rush@mit.edu"
color = "#cc4331"

[dorms."East Campus"]
contact = "ec-rex-chairs-25@mit.edu"
color = "#aa0000"

[dorms."MacGregor House"]
contact = "mac-rex-chairs@mit.edu"
color = "#ad6f65"

[dorms."Maseeh Hall"]
contact = "maseeh-rex-chair@mit.edu"
color = "#1f3a6c"

[dorms."McCormick Hall"]
contact = "mccormick-rex@mit.edu"
color = "#293142"

[dorms."New House"]
contact = "nh-rush@mit.edu"
color = "#e7e9f6"

[dorms."New Vassar"]
contact = "nv-rex-chair@mit.edu"
color = "#A62B0C"

[dorms."Next House"]
contact = "next-rex-comm@mit.edu"
color = "#34495e"

[dorms."Random Hall"]
contact = "random-rush-chair@mit.edu"
color = "#cf2661"

[dorms."Simmons Hall"]
contact = "simmons-frosh-chairs@mit.edu"
color = "#25aae1"

[dorms."DormCon"]
contact = "dormcon-rexvp@mit.edu"
color = "#4a8faf"
rename_to = "Campus Wide!"
